# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c8103c5e020a85667bbce2684bc480762cea958fbe8d21be1b19a11d013b3b2565ed3b216fa97203ee97f3465b6fe99d678be2babd304be65b9ed177de9db3c

test:
  secret_key_base: c6e04d0161daa7db7a97818408c36aaf9fa54438177b3f7a3a0341d6ae6bf508c8359181fb1944c2926fa914e4818e214ab4173e63e7700cf5215be682b23e07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
